---
# See https://golangci-lint.run/ for linters to enable and configure
linters:
  enable:
    - gofmt
    - cyclop # Checks function and package cyclomatic complexity
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - gosec # Inspects source code for security problems
    - funlen # Tool for detection of long functions
    - gosimple # Linter for Go source code that specializes in simplifying a code
    - gocritic # Provides many diagnostics that check for bugs, performance and style issues.
    - makezero # Finds slice declarations with non-zero initial length
    - revive # Extra fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - noctx
    - bodyclose
    - errorlint

issues:
  exclude-rules:
    - path: _test.go
      # Disable these rules for tests
      linters:
        - funlen

run:
  timeout: 3m
