schema:
  # Path to a local file in which the schema can be found
  path: "./schema.graphql"

persisted_operations:
  enabled: true
  # Store is the location on local disk where graphql-protect can find the persisted operations, it loads any `*.json` files on disk
  store: "./store"

max_aliases:
  # Enable the feature
  enabled: true
  # The maximum number of allowed aliases within a single request.
  max: 15

block_field_suggestions:
  enabled: true
  mask: "[redacted]"

max_depth:
  enabled: true
  # The maximum allowed depth within a single request.
  max: 15

max_tokens:
  # Enable the feature
  enabled: true
  # The maximum number of allowed tokens within a single request.
  max: 10000

max_batch:
  # Enable the feature
  enabled: true
  # The maximum number of operations within a single batched request.
  max: 5
